name: MyStandardPlugin
main: com.flashyee.myStandardPlugin.Main
version: 1.0
description: 世界商店
author: FlashYee
commands:
  shop:
    description: 呼叫商店
  money:
    description: 查看金錢
  sell:
    description: 以輸入的金額販售手上的物品